name: Java CI/CD Automation with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build and Verify with Maven (Includes JaCoCo)
        run: mvn clean verify

      - name: Run Checkstyle Reviewer Bot
        if: always()
        uses: dbelyaev/action-checkstyle@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: heheheheheheh.xml
          level: warning