name: Java CI/CD Automation with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ] # BƯỚC 1: Kích hoạt khi có Pull Request

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # CẤP QUYỀN: Bắt buộc phải có để Bot có quyền ghi bình luận vào PR
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build and Verify with Maven (Includes JaCoCo)
        run: mvn clean verify

      # BƯỚC 2: Tích hợp Inline Feedback Bot
      - name: Run Checkstyle Reviewer Bot
        if: always() # Luôn luôn chạy kể cả khi bước build trên bị fail để báo lỗi code
        uses: dbelyaev/action-checkstyle@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: src/main/resources/google_checks.xm # Sử dụng đúng file cấu hình của dự án
          level: warning